-- Migration: AODE (Asymmetric Opportunity Discovery Engine) core tables
-- Phase 1: Discovery, research reports, narratives, smart money, on-chain, developer, community

BEGIN;

-- 1. Discovered tokens (from Discovery Engine)
CREATE TABLE IF NOT EXISTS discovered_tokens (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(30) NOT NULL,
    chain VARCHAR(20) NOT NULL,
    contract_address VARCHAR(100),
    source VARCHAR(50) NOT NULL,
    name VARCHAR(200),
    market_cap_usd NUMERIC(24, 2),
    volume_24h_usd NUMERIC(24, 2),
    liquidity_usd NUMERIC(24, 2),
    price_usd NUMERIC(24, 8),
    price_change_24h_pct NUMERIC(8, 4),
    fdv NUMERIC(24, 2),
    discovered_at TIMESTAMP DEFAULT NOW(),
    last_updated_at TIMESTAMP DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'NEW' CHECK (status IN ('NEW', 'RESEARCHING', 'SCORED', 'WATCHLIST', 'ARCHIVED', 'REJECTED'))
);
CREATE INDEX IF NOT EXISTS idx_discovered_tokens_symbol ON discovered_tokens(symbol);
CREATE INDEX IF NOT EXISTS idx_discovered_tokens_chain ON discovered_tokens(chain);
CREATE INDEX IF NOT EXISTS idx_discovered_tokens_status ON discovered_tokens(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_discovered_tokens_unique
    ON discovered_tokens(symbol, chain, COALESCE(contract_address, ''));

-- 2. Research reports (generated by LLM agents)
CREATE TABLE IF NOT EXISTS research_reports (
    id BIGSERIAL PRIMARY KEY,
    token_id BIGINT REFERENCES discovered_tokens(id),
    symbol VARCHAR(30) NOT NULL,
    report_type VARCHAR(30) NOT NULL CHECK (report_type IN ('full', 'quick', 'update')),
    fundamental_score NUMERIC(5, 2),
    narrative_score NUMERIC(5, 2),
    smart_money_score NUMERIC(5, 2),
    onchain_score NUMERIC(5, 2),
    developer_score NUMERIC(5, 2),
    community_score NUMERIC(5, 2),
    market_score NUMERIC(5, 2),
    technical_score NUMERIC(5, 2),
    opportunity_score NUMERIC(5, 2),
    confidence NUMERIC(5, 2),
    risk_category VARCHAR(20) CHECK (risk_category IN ('LOW', 'MEDIUM', 'HIGH', 'EXTREME')),
    investment_bucket VARCHAR(20) CHECK (investment_bucket IN ('CORE', 'GROWTH', 'SPECULATIVE', 'MOONSHOT')),
    thesis TEXT,
    evidence JSONB,
    risks JSONB,
    recommendation VARCHAR(20) CHECK (recommendation IN ('BUY', 'WATCH', 'AVOID')),
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_research_symbol ON research_reports(symbol);
CREATE INDEX IF NOT EXISTS idx_research_score ON research_reports(opportunity_score DESC);
CREATE INDEX IF NOT EXISTS idx_research_created ON research_reports(created_at DESC);

-- 3. Narrative tracking
CREATE TABLE IF NOT EXISTS crypto_narratives (
    id BIGSERIAL PRIMARY KEY,
    narrative VARCHAR(50) NOT NULL,
    strength NUMERIC(5, 2),
    momentum VARCHAR(20) CHECK (momentum IN ('increasing', 'stable', 'decreasing')),
    confidence NUMERIC(5, 2),
    key_tokens JSONB,
    sources JSONB,
    detected_at TIMESTAMP DEFAULT NOW(),
    last_updated_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_narratives_name ON crypto_narratives(narrative);
CREATE INDEX IF NOT EXISTS idx_narratives_detected ON crypto_narratives(detected_at DESC);

-- 4. Smart money wallet tracking
CREATE TABLE IF NOT EXISTS smart_money_wallets (
    id BIGSERIAL PRIMARY KEY,
    address VARCHAR(100) NOT NULL,
    chain VARCHAR(20) NOT NULL,
    label VARCHAR(100),
    wallet_type VARCHAR(30) CHECK (wallet_type IN ('vc', 'whale', 'team', 'foundation', 'trader')),
    total_value_usd NUMERIC(24, 2),
    last_active_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(address, chain)
);

-- 5. Smart money transactions
CREATE TABLE IF NOT EXISTS smart_money_transactions (
    id BIGSERIAL PRIMARY KEY,
    wallet_id BIGINT REFERENCES smart_money_wallets(id),
    symbol VARCHAR(30) NOT NULL,
    chain VARCHAR(20) NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL', 'ADD_LIQ', 'REMOVE_LIQ')),
    amount_usd NUMERIC(24, 2),
    token_amount NUMERIC(24, 8),
    tx_hash VARCHAR(100),
    detected_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sm_tx_wallet ON smart_money_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_sm_tx_symbol ON smart_money_transactions(symbol);
CREATE INDEX IF NOT EXISTS idx_sm_tx_detected ON smart_money_transactions(detected_at DESC);

-- 6. On-chain intelligence snapshots
CREATE TABLE IF NOT EXISTS onchain_snapshots (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(30) NOT NULL,
    chain VARCHAR(20) NOT NULL,
    holder_count INT,
    top10_holder_pct NUMERIC(8, 4),
    tvl_usd NUMERIC(24, 2),
    dex_volume_24h_usd NUMERIC(24, 2),
    liquidity_usd NUMERIC(24, 2),
    unique_wallets_24h INT,
    transaction_count_24h INT,
    exchange_inflow_usd NUMERIC(24, 2),
    exchange_outflow_usd NUMERIC(24, 2),
    snapshot_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_onchain_symbol ON onchain_snapshots(symbol);
CREATE INDEX IF NOT EXISTS idx_onchain_snapshot ON onchain_snapshots(snapshot_at DESC);

-- 7. Developer activity snapshots
CREATE TABLE IF NOT EXISTS developer_snapshots (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(30) NOT NULL,
    repo_url VARCHAR(500),
    stars INT,
    forks INT,
    open_issues INT,
    commits_30d INT,
    contributors_30d INT,
    pull_requests_30d INT,
    last_commit_at TIMESTAMP,
    documentation_score NUMERIC(5, 2),
    snapshot_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_devsnap_symbol ON developer_snapshots(symbol);
CREATE INDEX IF NOT EXISTS idx_devsnap_snapshot ON developer_snapshots(snapshot_at DESC);

-- 8. Community metrics snapshots
CREATE TABLE IF NOT EXISTS community_snapshots (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(30) NOT NULL,
    platform VARCHAR(20) NOT NULL,
    member_count INT,
    active_count INT,
    growth_rate_7d NUMERIC(8, 4),
    sentiment_score NUMERIC(5, 2),
    bot_ratio NUMERIC(5, 4),
    engagement_rate NUMERIC(8, 4),
    snapshot_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_commsnap_symbol ON community_snapshots(symbol);
CREATE INDEX IF NOT EXISTS idx_commsnap_snapshot ON community_snapshots(snapshot_at DESC);

-- 9. Portfolio allocation buckets
CREATE TABLE IF NOT EXISTS portfolio_allocations (
    id BIGSERIAL PRIMARY KEY,
    bucket VARCHAR(20) NOT NULL CHECK (bucket IN ('CORE', 'GROWTH', 'SPECULATIVE', 'MOONSHOT')),
    target_pct NUMERIC(5, 2) NOT NULL,
    current_pct NUMERIC(5, 2),
    positions JSONB,
    rebalance_needed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 10. Research audit trail
CREATE TABLE IF NOT EXISTS research_audit_log (
    id BIGSERIAL PRIMARY KEY,
    token_symbol VARCHAR(30) NOT NULL,
    action VARCHAR(50) NOT NULL,
    details JSONB,
    agent VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_research_audit_symbol ON research_audit_log(token_symbol);
CREATE INDEX IF NOT EXISTS idx_research_audit_created ON research_audit_log(created_at DESC);

COMMIT;
