global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'karsa-orchestrator'
    static_configs:
      - targets: ['karsa-orchestrator:8000']
    metrics_path: '/metrics'

  - job_name: 'karsa-crypto-orchestrator'
    static_configs:
      - targets: ['karsa-crypto-orchestrator:8001']
    metrics_path: '/metrics'

  - job_name: 'karsa-crypto-bot'
    static_configs:
      - targets: ['karsa-crypto-bot:8444']
    metrics_path: '/metrics'
