global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "9router"
    static_configs:
      - targets: ["karsa-9router:20128"]
    metrics_path: /metrics

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: /metrics

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    metrics_path: /metrics
