-- Karsa Trading System - PostgreSQL Schema

-- 1. Portfolio State (Manual entry — no broker sync)
CREATE TABLE IF NOT EXISTS portfolio_state (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    market VARCHAR(10) NOT NULL CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    quantity DECIMAL(18, 4) NOT NULL,
    avg_cost DECIMAL(18, 4) NOT NULL,
    current_price DECIMAL(18, 4),
    unrealized_pnl DECIMAL(18, 4),
    notes TEXT,
    added_at TIMESTAMP DEFAULT NOW(),
    last_synced_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(ticker, market)
);

-- 1b. Cash Balance (per currency)
CREATE TABLE IF NOT EXISTS cash_balance (
    id SERIAL PRIMARY KEY,
    currency VARCHAR(5) NOT NULL CHECK (currency IN ('IDR', 'USD')),
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(currency)
);

INSERT INTO cash_balance (currency, balance) VALUES ('IDR', 0), ('USD', 0) ON CONFLICT DO NOTHING;

-- 2. Signals (Generated by Agents)
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(20) NOT NULL,
    market VARCHAR(10) NOT NULL CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    strategy VARCHAR(50) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('LONG', 'SHORT', 'CLOSE')),
    confidence_score INT CHECK (confidence_score >= 0 AND confidence_score <= 100),
    entry_price DECIMAL(18, 4),
    target_price DECIMAL(18, 4),
    stop_loss_price DECIMAL(18, 4),
    risk_reward_ratio DECIMAL(5, 2),
    reasoning TEXT,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')),
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP
);

-- 3. Paper Positions (Shadow Execution Engine)
CREATE TABLE IF NOT EXISTS paper_positions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID REFERENCES signals(id) ON DELETE SET NULL,
    ticker VARCHAR(20) NOT NULL,
    market VARCHAR(10) NOT NULL CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    side VARCHAR(10) NOT NULL CHECK (side IN ('LONG', 'SHORT')),
    quantity DECIMAL(18, 4) NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL,
    current_price DECIMAL(18, 4),
    target_price DECIMAL(18, 4),
    stop_loss_price DECIMAL(18, 4),
    atr_at_entry DECIMAL(18, 4),
    sizing_method VARCHAR(50) DEFAULT 'volatility_target',
    unrealized_pnl DECIMAL(18, 4),
    unrealized_pnl_pct DECIMAL(8, 4),
    max_drawdown_pct DECIMAL(8, 4),
    entry_date TIMESTAMP DEFAULT NOW(),
    notes TEXT,
    UNIQUE(signal_id)
);

-- 4. Closed Paper Trades (Archive for P&L Tracking)
CREATE TABLE IF NOT EXISTS closed_paper_trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID,
    ticker VARCHAR(20) NOT NULL,
    market VARCHAR(10) NOT NULL CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    side VARCHAR(10) NOT NULL CHECK (side IN ('LONG', 'SHORT')),
    quantity DECIMAL(18, 4) NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL,
    exit_price DECIMAL(18, 4) NOT NULL,
    realized_pnl DECIMAL(18, 4),
    realized_pnl_pct DECIMAL(8, 4),
    entry_date TIMESTAMP,
    exit_date TIMESTAMP DEFAULT NOW(),
    hold_duration INTERVAL,
    exit_reason VARCHAR(50),
    strategy VARCHAR(50),
    notes TEXT
);

-- 4. Immutable Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGSERIAL PRIMARY KEY,
    component VARCHAR(50) NOT NULL CHECK (component IN ('ORCHESTRATOR', 'IDX_AGENT', 'US_AGENT', 'ETF_AGENT', 'CRYPTO_AGENT', 'RISK_AGENT', 'TELEGRAM', 'BROKER')),
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50),
    entity_id UUID,
    payload JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 5. Historical OHLCV Cache
CREATE TABLE IF NOT EXISTS ohlcv_cache (
    ticker VARCHAR(20),
    market VARCHAR(10) CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    timeframe VARCHAR(5) CHECK (timeframe IN ('1m', '5m', '15m', '1h', '4h', '1D')),
    timestamp TIMESTAMP,
    open DECIMAL(18, 4),
    high DECIMAL(18, 4),
    low DECIMAL(18, 4),
    close DECIMAL(18, 4),
    volume BIGINT,
    PRIMARY KEY (ticker, market, timeframe, timestamp)
);

-- 6. Market Holidays
CREATE TABLE IF NOT EXISTS market_holidays (
    market VARCHAR(10) NOT NULL CHECK (market IN ('IDX', 'US')),
    holiday_date DATE NOT NULL,
    name VARCHAR(100),
    PRIMARY KEY (market, holiday_date)
);

-- 7. Pending Approvals (for HITL flow)
CREATE TABLE IF NOT EXISTS pending_approvals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID REFERENCES signals(id) ON DELETE SET NULL,
    telegram_message_id BIGINT,
    status VARCHAR(20) DEFAULT 'WAITING' CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXPIRED')),
    modification JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_paper_positions_ticker ON paper_positions(ticker, market);
CREATE INDEX IF NOT EXISTS idx_paper_positions_entry ON paper_positions(entry_date DESC);
CREATE INDEX IF NOT EXISTS idx_closed_paper_trades_ticker ON closed_paper_trades(ticker, market);
CREATE INDEX IF NOT EXISTS idx_closed_paper_trades_exit ON closed_paper_trades(exit_date DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_component ON audit_logs(component);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ohlcv_ticker ON ohlcv_cache(ticker, market, timeframe);
CREATE INDEX IF NOT EXISTS idx_pending_approvals_status ON pending_approvals(status);

-- Insert default market holidays (example)
INSERT INTO market_holidays (market, holiday_date, name) VALUES
    ('IDX', '2026-01-01', 'New Year'),
    ('IDX', '2026-01-29', 'Isra Mi''raj'),
    ('IDX', '2026-01-30', 'Chinese New Year'),
    ('IDX', '2026-03-20', 'Hari Raya Nyepi'),
    ('IDX', '2026-03-27', 'Wafat Isa Al Masih'),
    ('IDX', '2026-04-01', 'Idul Fitri'),
    ('IDX', '2026-04-02', 'Idul Fitri'),
    ('IDX', '2026-04-03', 'Idul Fitri cuti bersama'),
    ('IDX', '2026-05-14', 'Kenaikan Isa Al Masih'),
    ('IDX', '2026-05-22', 'Waisak'),
    ('IDX', '2026-06-08', 'Idul Adha'),
    ('IDX', '2026-06-29', 'Tahun Baru Islam'),
    ('IDX', '2026-08-17', 'Hari Kemerdekaan'),
    ('IDX', '2026-09-07', 'Maulid Nabi'),
    ('IDX', '2026-12-25', 'Natal'),
    ('US', '2026-01-01', 'New Year'),
    ('US', '2026-01-19', 'Martin Luther King Jr. Day'),
    ('US', '2026-02-16', 'Presidents'' Day'),
    ('US', '2026-04-03', 'Good Friday'),
    ('US', '2026-05-25', 'Memorial Day'),
    ('US', '2026-06-19', 'Juneteenth'),
    ('US', '2026-07-03', 'Independence Day (observed)'),
    ('US', '2026-09-07', 'Labor Day'),
    ('US', '2026-11-26', 'Thanksgiving'),
    ('US', '2026-12-25', 'Christmas')
ON CONFLICT DO NOTHING;

-- Append-only enforcement (no UPDATE or DELETE on immutable tables)
-- These rules prevent accidental mutation of audit trail and closed trade history.
-- Signals and paper_positions NEED updates (status changes, price updates) — no rules there.
CREATE RULE no_update_audit AS ON UPDATE TO audit_logs DO INSTEAD NOTHING;
CREATE RULE no_delete_audit AS ON DELETE TO audit_logs DO INSTEAD NOTHING;
CREATE RULE no_update_closed_trade AS ON UPDATE TO closed_paper_trades DO INSTEAD NOTHING;
CREATE RULE no_delete_closed_trade AS ON DELETE TO closed_paper_trades DO INSTEAD NOTHING;

-- Performance indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_signals_ticker_market_status ON signals(ticker, market, status);
CREATE INDEX IF NOT EXISTS idx_pending_approvals_signal ON pending_approvals(signal_id);

-- 8. Reasoning Traces (Phase 2: Agent reasoning capture)
CREATE TABLE IF NOT EXISTS reasoning_traces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_id UUID,
    agent_name VARCHAR(50) NOT NULL,
    ticker VARCHAR(20),
    market VARCHAR(10) CHECK (market IN ('IDX', 'US', 'ETF', 'CRYPTO')),
    system_prompt TEXT NOT NULL,
    user_prompt TEXT NOT NULL,
    tools_used JSONB,
    tool_results JSONB,
    llm_response TEXT,
    reasoning_extracted TEXT,
    strategy_used VARCHAR(100),
    regime_at_time VARCHAR(20),
    confidence_score INT,
    iterations INT DEFAULT 1,
    model_used VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_traces_ticker ON reasoning_traces(ticker, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_traces_signal ON reasoning_traces(signal_id);

-- 9. Strategy Recommendations (Phase 4: Self-improvement)
CREATE TABLE IF NOT EXISTS strategy_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recommendation_type VARCHAR(50) NOT NULL,
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    expected_impact VARCHAR(200),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'APPLIED')),
    metrics_snapshot JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    applied_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON strategy_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_recommendations_priority ON strategy_recommendations(priority);

-- 10. Crypto Positions (Bybit perpetuals mirror)
CREATE TABLE IF NOT EXISTS crypto_positions (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    size NUMERIC(18, 8) NOT NULL,
    entry_price NUMERIC(18, 4) NOT NULL,
    current_price NUMERIC(18, 4),
    leverage INT DEFAULT 1,
    margin_mode VARCHAR(10) DEFAULT 'isolated',
    liquidation_price NUMERIC(18, 4),
    unrealized_pnl NUMERIC(18, 4),
    funding_cost_cumulative NUMERIC(18, 4) DEFAULT 0,
    stop_loss NUMERIC(18, 4),
    take_profit NUMERIC(18, 4),
    exchange_position_id VARCHAR(100),
    status VARCHAR(20) DEFAULT 'OPEN',
    opened_at TIMESTAMP DEFAULT NOW(),
    last_synced_at TIMESTAMP DEFAULT NOW(),
    trailing_stop_price NUMERIC(18, 4),
    highest_price NUMERIC(18, 4),
    entry_funding_rate NUMERIC(12, 8),
    regime_at_entry VARCHAR(20),
    signal_source VARCHAR(50),
    partial_exits_taken INT DEFAULT 0,
    last_management_check TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_crypto_positions_status ON crypto_positions(status);
CREATE INDEX IF NOT EXISTS idx_crypto_positions_ticker ON crypto_positions(ticker);

-- 11. Crypto Funding Payments
CREATE TABLE IF NOT EXISTS crypto_funding_payments (
    id BIGSERIAL PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    funding_rate NUMERIC(12, 8) NOT NULL,
    funding_fee NUMERIC(18, 4) NOT NULL,
    position_size NUMERIC(18, 8),
    side VARCHAR(10),
    funded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_funding_ticker ON crypto_funding_payments(ticker, funded_at DESC);

-- 12. Crypto PnL Snapshots (daily equity curve)
CREATE TABLE IF NOT EXISTS crypto_pnl_snapshots (
    id BIGSERIAL PRIMARY KEY,
    snapshot_date TIMESTAMP NOT NULL DEFAULT NOW(),
    equity NUMERIC(18, 4) NOT NULL,
    realized_pnl NUMERIC(18, 4) DEFAULT 0,
    unrealized_pnl NUMERIC(18, 4) DEFAULT 0,
    funding_costs NUMERIC(18, 4) DEFAULT 0,
    total_pnl NUMERIC(18, 4) DEFAULT 0,
    open_positions INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pnl_snapshots_date ON crypto_pnl_snapshots(snapshot_date DESC);

-- 13. Crypto Regime History
CREATE TABLE IF NOT EXISTS crypto_regime_history (
    id BIGSERIAL PRIMARY KEY,
    regime VARCHAR(20) NOT NULL,
    hurst NUMERIC(6, 4),
    adx NUMERIC(6, 2),
    btc_dominance NUMERIC(6, 2),
    market_season VARCHAR(20),
    details JSONB,
    timestamp TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_regime_history_ts ON crypto_regime_history(timestamp DESC);

-- 14. Crypto Trailing Stops (audit trail)
CREATE TABLE IF NOT EXISTS crypto_trailing_stops (
    id BIGSERIAL PRIMARY KEY,
    position_id BIGINT NOT NULL REFERENCES crypto_positions(id),
    old_price NUMERIC(18, 4),
    new_price NUMERIC(18, 4) NOT NULL,
    trigger_price NUMERIC(18, 4),
    reason VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_trailing_stops_position ON crypto_trailing_stops(position_id);

-- 15. Crypto Partial Exits
CREATE TABLE IF NOT EXISTS crypto_partial_exits (
    id BIGSERIAL PRIMARY KEY,
    position_id BIGINT NOT NULL REFERENCES crypto_positions(id),
    exit_pct INT NOT NULL,
    exit_price NUMERIC(18, 4) NOT NULL,
    exit_qty NUMERIC(18, 8) NOT NULL,
    pnl_usdt NUMERIC(18, 4),
    reason VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_partial_exits_position ON crypto_partial_exits(position_id);

-- 16. Crypto Circuit Breaker Events
CREATE TABLE IF NOT EXISTS crypto_circuit_breaker_events (
    id BIGSERIAL PRIMARY KEY,
    breaker_type VARCHAR(20) NOT NULL CHECK (breaker_type IN ('DAILY_DD', 'VOLATILITY', 'CORRELATION')),
    severity VARCHAR(10) NOT NULL CHECK (severity IN ('WARNING', 'HALT')),
    details JSONB,
    triggered_at TIMESTAMP DEFAULT NOW(),
    resolved_at TIMESTAMP
);

-- 17. Crypto Reconciliation Logs
CREATE TABLE IF NOT EXISTS crypto_reconciliation_logs (
    id BIGSERIAL PRIMARY KEY,
    position_id BIGINT,
    drift_type VARCHAR(20) NOT NULL CHECK (drift_type IN ('PHANTOM', 'MISSING', 'SIZE_DRIFT')),
    exchange_state JSONB,
    db_state JSONB,
    resolution VARCHAR(50),
    detected_at TIMESTAMP DEFAULT NOW()
);

-- Partitioning guidance (apply when tables grow large):
-- ohlcv_cache: RANGE partition on timestamp (monthly)
-- audit_logs: RANGE partition on created_at (monthly)
-- Consider pg_partman for automated partition management.
