"""Karsa Trading System - SQLAlchemy ORM Models"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import String, Integer, BigInteger, Numeric, DateTime, Text, JSON, ForeignKey, CheckConstraint, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.database import Base


class CashBalance(Base):
    """Cash balance per currency."""
    __tablename__ = "cash_balance"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    currency: Mapped[str] = mapped_column(String(5), nullable=False)
    balance: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False, default=0)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("currency", name="uq_cash_balance_currency"),
        CheckConstraint("currency IN ('IDR', 'USD')", name="ck_cash_currency"),
    )


class PortfolioState(Base):
    """Portfolio positions — manually managed."""
    __tablename__ = "portfolio_state"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    avg_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    current_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    unrealized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    notes: Mapped[str | None] = mapped_column(Text)
    added_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_synced_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("ticker", "market", name="uq_portfolio_ticker_market"),
        CheckConstraint("market IN ('IDX', 'US', 'ETF')", name="ck_portfolio_market"),
    )


class Signal(Base):
    """Trading signals generated by agents."""
    __tablename__ = "signals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    strategy: Mapped[str] = mapped_column(String(50), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    confidence_score: Mapped[int | None] = mapped_column(Integer)
    entry_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    target_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    stop_loss_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    risk_reward_ratio: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    reasoning: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime)

    trades: Mapped[list["Trade"]] = relationship(back_populates="signal")
    approval: Mapped["PendingApproval | None"] = relationship(back_populates="signal")

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF')", name="ck_signal_market"),
        CheckConstraint("direction IN ('LONG', 'SHORT', 'CLOSE')", name="ck_signal_direction"),
        CheckConstraint("confidence_score >= 0 AND confidence_score <= 100", name="ck_signal_confidence"),
        CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')", name="ck_signal_status"),
    )


class Trade(Base):
    """Trade execution records."""
    __tablename__ = "trades"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("signals.id"))
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    order_type: Mapped[str] = mapped_column(String(20), default="LIMIT")
    limit_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    filled_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    filled_quantity: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    broker_order_id: Mapped[str | None] = mapped_column(String(100))
    idempotency_key: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), unique=True, default=uuid.uuid4)
    rejection_reason: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    signal: Mapped["Signal | None"] = relationship(back_populates="trades")

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF')", name="ck_trade_market"),
        CheckConstraint("side IN ('BUY', 'SELL')", name="ck_trade_side"),
        CheckConstraint("order_type IN ('LIMIT', 'MARKET', 'STOP')", name="ck_trade_order_type"),
        CheckConstraint("status IN ('PENDING', 'FILLED', 'PARTIAL', 'REJECTED', 'CANCELLED')", name="ck_trade_status"),
    )


class AuditLog(Base):
    """Immutable audit logs for all system actions."""
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    component: Mapped[str] = mapped_column(String(50), nullable=False)
    action: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_type: Mapped[str | None] = mapped_column(String(50))
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    payload: Mapped[dict] = mapped_column(JSON, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint(
            "component IN ('ORCHESTRATOR', 'IDX_AGENT', 'US_AGENT', 'ETF_AGENT', 'RISK_AGENT', 'TELEGRAM', 'BROKER')",
            name="ck_audit_component"
        ),
    )


class OHLCVCache(Base):
    """Historical OHLCV price data cache."""
    __tablename__ = "ohlcv_cache"

    ticker: Mapped[str] = mapped_column(String(20), primary_key=True)
    market: Mapped[str] = mapped_column(String(10), primary_key=True)
    timeframe: Mapped[str] = mapped_column(String(5), primary_key=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, primary_key=True)
    open: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    high: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    low: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    close: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    volume: Mapped[int] = mapped_column(BigInteger)

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF')", name="ck_ohlcv_market"),
        CheckConstraint("timeframe IN ('1m', '5m', '15m', '1h', '4h', '1D')", name="ck_ohlcv_timeframe"),
    )


class MarketHoliday(Base):
    """Market holiday calendar."""
    __tablename__ = "market_holidays"

    market: Mapped[str] = mapped_column(String(10), primary_key=True)
    holiday_date: Mapped[datetime] = mapped_column(DateTime, primary_key=True)
    name: Mapped[str | None] = mapped_column(String(100))

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US')", name="ck_holiday_market"),
    )


class PendingApproval(Base):
    """Pending trade approvals for HITL flow."""
    __tablename__ = "pending_approvals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("signals.id"))
    telegram_message_id: Mapped[int | None] = mapped_column(BigInteger)
    status: Mapped[str] = mapped_column(String(20), default="WAITING")
    modification: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    responded_at: Mapped[datetime | None] = mapped_column(DateTime)

    signal: Mapped["Signal | None"] = relationship(back_populates="approval")

    __table_args__ = (
        CheckConstraint("status IN ('WAITING', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXPIRED')", name="ck_approval_status"),
    )
