"""Karsa Trading System - SQLAlchemy ORM Models"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import String, Integer, BigInteger, Numeric, DateTime, Text, JSON, ForeignKey, CheckConstraint, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.database import Base


class CashBalance(Base):
    """Cash balance per currency."""
    __tablename__ = "cash_balance"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    currency: Mapped[str] = mapped_column(String(5), nullable=False)
    balance: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False, default=0)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("currency", name="uq_cash_balance_currency"),
        CheckConstraint("currency IN ('IDR', 'USD')", name="ck_cash_currency"),
    )


class PortfolioState(Base):
    """Portfolio positions — manually managed."""
    __tablename__ = "portfolio_state"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    avg_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    current_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    unrealized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    notes: Mapped[str | None] = mapped_column(Text)
    added_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_synced_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("ticker", "market", name="uq_portfolio_ticker_market"),
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_portfolio_market"),
    )


class Signal(Base):
    """Trading signals generated by agents."""
    __tablename__ = "signals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    strategy: Mapped[str] = mapped_column(String(50), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    confidence_score: Mapped[int | None] = mapped_column(Integer)
    entry_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    target_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    stop_loss_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    risk_reward_ratio: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    reasoning: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime)

    paper_positions: Mapped[list["PaperPosition"]] = relationship(back_populates="signal")
    approval: Mapped["PendingApproval | None"] = relationship(back_populates="signal")

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_signal_market"),
        CheckConstraint("direction IN ('LONG', 'SHORT', 'CLOSE')", name="ck_signal_direction"),
        CheckConstraint("confidence_score >= 0 AND confidence_score <= 100", name="ck_signal_confidence"),
        CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')", name="ck_signal_status"),
    )


class PaperPosition(Base):
    """Paper trading positions (Shadow Execution Engine)."""
    __tablename__ = "paper_positions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("signals.id"), unique=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    current_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    target_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    stop_loss_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    atr_at_entry: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    sizing_method: Mapped[str] = mapped_column(String(50), default="volatility_target")
    unrealized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    unrealized_pnl_pct: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    max_drawdown_pct: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    entry_date: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    notes: Mapped[str | None] = mapped_column(Text)

    signal: Mapped["Signal | None"] = relationship(back_populates="paper_positions")

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_paper_market"),
        CheckConstraint("side IN ('LONG', 'SHORT')", name="ck_paper_side"),
    )


class ClosedPaperTrade(Base):
    """Archive of closed paper trades for P&L tracking."""
    __tablename__ = "closed_paper_trades"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    market: Mapped[str] = mapped_column(String(10), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    exit_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    realized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    realized_pnl_pct: Mapped[Decimal | None] = mapped_column(Numeric(8, 4))
    entry_date: Mapped[datetime | None] = mapped_column(DateTime)
    exit_date: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    hold_duration: Mapped[datetime | None] = mapped_column(DateTime)  # Interval not supported well in SQLAlchemy
    exit_reason: Mapped[str | None] = mapped_column(String(50))
    strategy: Mapped[str | None] = mapped_column(String(50))
    notes: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_closed_market"),
        CheckConstraint("side IN ('LONG', 'SHORT')", name="ck_closed_side"),
    )


class AuditLog(Base):
    """Immutable audit logs for all system actions."""
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    component: Mapped[str] = mapped_column(String(50), nullable=False)
    action: Mapped[str] = mapped_column(String(50), nullable=False)
    entity_type: Mapped[str | None] = mapped_column(String(50))
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    payload: Mapped[dict] = mapped_column(JSON, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint(
            "component IN ('ORCHESTRATOR', 'IDX_AGENT', 'US_AGENT', 'ETF_AGENT', 'CRYPTO_AGENT', 'RISK_AGENT', 'TELEGRAM', 'BROKER')",
            name="ck_audit_component"
        ),
    )


class OHLCVCache(Base):
    """Historical OHLCV price data cache."""
    __tablename__ = "ohlcv_cache"

    ticker: Mapped[str] = mapped_column(String(20), primary_key=True)
    market: Mapped[str] = mapped_column(String(10), primary_key=True)
    timeframe: Mapped[str] = mapped_column(String(5), primary_key=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, primary_key=True)
    open: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    high: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    low: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    close: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    volume: Mapped[int] = mapped_column(BigInteger)

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_ohlcv_market"),
        CheckConstraint("timeframe IN ('1m', '5m', '15m', '1h', '4h', '1D')", name="ck_ohlcv_timeframe"),
    )


class MarketHoliday(Base):
    """Market holiday calendar."""
    __tablename__ = "market_holidays"

    market: Mapped[str] = mapped_column(String(10), primary_key=True)
    holiday_date: Mapped[datetime] = mapped_column(DateTime, primary_key=True)
    name: Mapped[str | None] = mapped_column(String(100))

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US')", name="ck_holiday_market"),
    )


class PendingApproval(Base):
    """Pending trade approvals for HITL flow."""
    __tablename__ = "pending_approvals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("signals.id"))
    telegram_message_id: Mapped[int | None] = mapped_column(BigInteger)
    status: Mapped[str] = mapped_column(String(20), default="WAITING")
    modification: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    responded_at: Mapped[datetime | None] = mapped_column(DateTime)

    signal: Mapped["Signal | None"] = relationship(back_populates="approval")

    __table_args__ = (
        CheckConstraint("status IN ('WAITING', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXPIRED')", name="ck_approval_status"),
    )


# --- Crypto-specific tables ---

class CryptoPosition(Base):
    """Local mirror of Bybit perpetual positions — survives API outages."""
    __tablename__ = "crypto_positions"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    size: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    current_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    leverage: Mapped[int] = mapped_column(Integer, default=1)
    margin_mode: Mapped[str] = mapped_column(String(10), default="isolated")
    liquidation_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    unrealized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    funding_cost_cumulative: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    stop_loss: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    take_profit: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    exchange_position_id: Mapped[str | None] = mapped_column(String(100))
    status: Mapped[str] = mapped_column(String(20), default="OPEN")
    opened_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    last_synced_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # --- Phase 1: Lifecycle management fields ---
    trailing_stop_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    highest_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    entry_funding_rate: Mapped[Decimal | None] = mapped_column(Numeric(12, 8))
    regime_at_entry: Mapped[str | None] = mapped_column(String(20))
    signal_source: Mapped[str | None] = mapped_column(String(50))
    partial_exits_taken: Mapped[int] = mapped_column(Integer, default=0)
    last_management_check: Mapped[datetime | None] = mapped_column(DateTime)

    __table_args__ = (
        CheckConstraint("side IN ('Buy', 'Sell')", name="ck_crypto_pos_side"),
        CheckConstraint("status IN ('OPEN', 'CLOSED', 'LIQUIDATED')", name="ck_crypto_pos_status"),
        CheckConstraint("leverage >= 1 AND leverage <= 100", name="ck_crypto_pos_leverage"),
    )


class CryptoFundingPayment(Base):
    """Funding payment log — tracks 8-hour funding costs."""
    __tablename__ = "crypto_funding_payments"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False)
    funding_rate: Mapped[Decimal] = mapped_column(Numeric(12, 8), nullable=False)
    funding_fee: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    position_size: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    funded_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    synced_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("ticker", "funded_at", name="uq_crypto_funding_ticker_time"),
    )


class CryptoRegimeHistory(Base):
    """Regime transition log for analysis."""
    __tablename__ = "crypto_regime_history"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    regime: Mapped[str] = mapped_column(String(20), nullable=False)
    hurst: Mapped[Decimal | None] = mapped_column(Numeric(4, 3))
    adx: Mapped[Decimal | None] = mapped_column(Numeric(6, 2))
    volatility_regime: Mapped[str | None] = mapped_column(String(20))
    btc_dominance: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    size_multiplier: Mapped[Decimal | None] = mapped_column(Numeric(3, 2))
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint(
            "regime IN ('FULL_TREND_ALIGNMENT', 'MACRO_BULL_MICRO_PULLBACK', 'MACRO_BEAR_MICRO_PULLBACK', 'MICRO_BREAKOUT_NO_MACRO', 'MEAN_REVERSION', 'PURE_DEAD_CHOP', 'UNKNOWN')",
            name="ck_crypto_regime"
        ),
    )


class CryptoPnLSnapshot(Base):
    """Daily PnL snapshots."""
    __tablename__ = "crypto_pnl_snapshots"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    snapshot_date: Mapped[datetime] = mapped_column(DateTime, nullable=False, unique=True)
    realized_pnl: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    unrealized_pnl: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    funding_costs: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    total_pnl: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    equity: Mapped[Decimal] = mapped_column(Numeric(18, 4), default=0)
    open_positions: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class CryptoTrailingStop(Base):
    """Trailing stop adjustment audit trail."""
    __tablename__ = "crypto_trailing_stops"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    position_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("crypto_positions.id"), nullable=False, index=True)
    old_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    new_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    trigger_price: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    reason: Mapped[str] = mapped_column(String(50), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class CryptoPartialExit(Base):
    """Partial exit history — tracks scale-out events."""
    __tablename__ = "crypto_partial_exits"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    position_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("crypto_positions.id"), nullable=False, index=True)
    exit_pct: Mapped[int] = mapped_column(Integer, nullable=False)
    exit_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    exit_qty: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    pnl_usdt: Mapped[Decimal | None] = mapped_column(Numeric(18, 4))
    reason: Mapped[str] = mapped_column(String(50), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)


class CryptoCircuitBreakerEvent(Base):
    """Circuit breaker trigger log."""
    __tablename__ = "crypto_circuit_breaker_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    breaker_type: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(10), nullable=False)
    details: Mapped[dict | None] = mapped_column(JSON)
    triggered_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime)

    __table_args__ = (
        CheckConstraint("breaker_type IN ('DAILY_DD', 'VOLATILITY', 'CORRELATION')", name="ck_cb_breaker_type"),
        CheckConstraint("severity IN ('WARNING', 'HALT')", name="ck_cb_severity"),
    )


class CryptoReconciliationLog(Base):
    """Position reconciliation drift log."""
    __tablename__ = "crypto_reconciliation_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    position_id: Mapped[int | None] = mapped_column(BigInteger)
    drift_type: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    exchange_state: Mapped[dict | None] = mapped_column(JSON)
    db_state: Mapped[dict | None] = mapped_column(JSON)
    resolution: Mapped[str | None] = mapped_column(String(50))
    detected_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)

    __table_args__ = (
        CheckConstraint("drift_type IN ('PHANTOM', 'MISSING', 'SIZE_DRIFT')", name="ck_recon_drift_type"),
    )


class ReasoningTrace(Base):
    """Agent reasoning traces — full LLM conversation log for analysis and replay."""
    __tablename__ = "reasoning_traces"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    signal_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), index=True)
    agent_name: Mapped[str] = mapped_column(String(50), nullable=False)
    ticker: Mapped[str | None] = mapped_column(String(20))
    market: Mapped[str | None] = mapped_column(String(10))
    system_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    user_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    tools_used: Mapped[list | None] = mapped_column(JSON)
    tool_results: Mapped[list | None] = mapped_column(JSON)
    llm_response: Mapped[str | None] = mapped_column(Text)
    reasoning_extracted: Mapped[str | None] = mapped_column(Text)
    strategy_used: Mapped[str | None] = mapped_column(String(100))
    regime_at_time: Mapped[str | None] = mapped_column(String(20))
    confidence_score: Mapped[int | None] = mapped_column(Integer)
    iterations: Mapped[int] = mapped_column(Integer, default=1)
    model_used: Mapped[str | None] = mapped_column(String(100))
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint("market IN ('IDX', 'US', 'ETF', 'CRYPTO')", name="ck_trace_market"),
    )


class StrategyRecommendation(Base):
    """LLM-generated strategy improvement recommendations from CryptoAuditor."""
    __tablename__ = "strategy_recommendations"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    recommendation_type: Mapped[str] = mapped_column(String(50), nullable=False)
    priority: Mapped[str] = mapped_column(String(10), nullable=False)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    expected_impact: Mapped[str | None] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    metrics_snapshot: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    applied_at: Mapped[datetime | None] = mapped_column(DateTime)

class CryptoAutoSession(Base):
    """Autonomous campaign session audit trail."""
    __tablename__ = "crypto_auto_sessions"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    config: Mapped[dict | None] = mapped_column(JSON)
    starting_equity: Mapped[Decimal | None] = mapped_column(Numeric(18, 2))
    ending_equity: Mapped[Decimal | None] = mapped_column(Numeric(18, 2))
    total_trades: Mapped[int] = mapped_column(Integer, default=0)
    wins: Mapped[int] = mapped_column(Integer, default=0)
    losses: Mapped[int] = mapped_column(Integer, default=0)
    realized_pnl: Mapped[Decimal] = mapped_column(Numeric(18, 2), default=0)
    unrealized_pnl: Mapped[Decimal] = mapped_column(Numeric(18, 2), default=0)
    status: Mapped[str] = mapped_column(String(20), default="RUNNING")
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        CheckConstraint("status IN ('RUNNING', 'STOPPED', 'CRASHED')", name="ck_auto_session_status"),
    )
